### ISSUE TITLE
Estimate Distributions Feature

### ISSUE THREAD

**Issue by tnoelcke** [osu-cass/usda-plant-breeding#6]
We need to estimate the Distributions feature.

**Comment by hertelc** [comment]
Outstanding estimates needed.  Mary – are you still interested in these?
3.	Distribution Tracking – Yes please estimate!
a.	This was started some time ago, but not finished.  This is now a high priority to get accomplished.  This tracking allows the team to know what plants went where and when. 
b.	Reports Mary talked about: 
i.	By year (everything that happened for a year)
ii.	By cultivar/selection (see who got it and when)
iii.	By grower (what does a given grower have)
c.	Thomas: Review current implementation and do some small cleanup to make it functional
d.	Thomas: Do some research on if there are other tools out there (maybe open source inventory tracking?) that could be used here
4.	Patent tracking – not sure on this one yet, but may be combined into the distribution tracking
a.	Currently has a few fields in the Accessions lists, but needs some expansion to track the status of patent.  Also need reporting to be able to pull patent status across the project.  Would like links with distribution tracking.
b.	Thomas: Review and provide an estimate
